name: "Update dependencies"
on:
  workflow_dispatch:
jobs:
  sync:
    name: "Sync dependencies"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_AUTH_TOKEN }}
          submodules: true
      - name: Update
        run: |
          git pull --recurse-submodules
          git submodule update --recursive --remote
      - name: Commit
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'bot@noreply.github.com'
          git add --all
          git commit -am "Update dependencies" || echo "No changes to commit"
          git push